### ISSUE TITLE
void-function heex-ts-mode-treesit-ready-p

### ISSUE THREAD

**Issue by djgoku** [wkirschbaum/heex-ts-mode#3]
Getting this message  `File mode specification error: (void-function heex-ts-mode-treesit-ready-p) [2 times]` with the following config.

Emacs version https://github.com/emacs-mirror/emacs/commit/146389f873e4e41940127c1ccb5df3f9cf357060
and the latest version of `elixir-ts-mode` and `heex-ts-mode`.
```
(setq treesit-extra-load-path '("/Users/dj_goku/dev/github/casouri/tree-sitter-module/dist"))

(use-package heex-ts-mode)

(use-package elixir-ts-mode)
   :config (global-subword-mode t))

(use-package eglot
  :config
  (dolist (mode '(elixir-ts-mode heex-ts-mode))
    (add-to-list 'eglot-server-programs `(,mode . ("/Users/dj_goku/dev/github/elixir-lsp/elixir-ls/release/language_server.sh"))))
  (add-to-list 'eglot-server-programs
               '((python-mode python-ts-mode) "pyright-langserver" "--stdio"))
  :hook ((elixir-ts-mode . eglot-ensure)
         (heex-ts-mode . eglot-ensure)
         (elixir-ts-mode . eglot-ensure)
         (python-mode . eglot-ensure)
         (python-ts-mode . eglot-ensure)))
```

**Comment by wkirschbaum** [comment]
Hi @djgoku. it is strange, because `heex-ts-mode-treesit-ready-p` is not being called anymore. loading of `heex-ts-mode' is automatic with `elixir-ts-mode'. 

{elixir,heex}-ts-modes are now part of emacs, so if you run on emacs master you can delete the packages, but still need to `(require 'elixir-ts-mode)`.

I will have a look on my side as well if there is anything strange.

**Comment by wkirschbaum** [comment]
You have a typo:
```elisp
(use-package elixir-ts-mode)
   :config (global-subword-mode t))
```
should be
```elisp
(use-package elixir-ts-mode
   :config (global-subword-mode t))
```

**Comment by wkirschbaum** [comment]
Okay, I see there is an issue. Will fix today.

**Comment by wkirschbaum** [comment]
@djgoku its should be fixed now

**Comment by djgoku** [comment]
It does! Thank you!
